### ISSUE TITLE
How to get entity by Guid

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/DynamicsCRMProvider#4]
When I try to query like this:
```fsharp
let getOpportunity (id:Guid) =
    query {
        for o in crm.opportunitySet do
        where (o.Id = id)
        select o
    }
    |> Seq.head
```
I get an error in runtime:
```
System.Exception: unsuppored member expression on left side
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
   at Microsoft.FSharp.Linq.QueryModule.clo@1737-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
   at FSI_0005.getOpportunity(Guid id) ...
```
@pezipink
Is it issue of DynamicsCRMProvider ? Does exist another way to get entity by guid?

**Comment by pezipink** [comment]
Just from memory here - that ID is likely a property that points at the real primary key field.  You need to change your query to the actual field, which will be something like opportunityId

**Comment by sergey-tihon** [comment]
Wow! Amazing memory! It work! Thank you! :+1:
